CREATE TABLE student (
    sid    INT         PRIMARY KEY,
    name   VARCHAR(60) NOT NULL ,
    gender CHAR,
    email  VARCHAR(60) NOT NULL
);

INSERT INTO student (sid, name, gender, email) VALUES (532, 'Pooh de Verson', 'M', 'pde0@sitemeter.com');
INSERT INTO student (sid, name, gender, email) VALUES (325, 'Myranda Etty', 'F', 'metty1@unesco.org');
INSERT INTO student (sid, name, gender, email) VALUES (727, 'Valene Christoffersen', 'F', 'vchristoffersen2@marketwatch.com');
INSERT INTO student (sid, name, gender, email) VALUES (349, 'Hillary Schellig', 'F', 'hschellig3@omniture.com');
INSERT INTO student (sid, name, gender, email) VALUES (570, 'Estell O'' Mahony', 'F', 'eo4@youku.com');
INSERT INTO student (sid, name, gender, email) VALUES (412, 'Teresina Stoppe', 'F', 'tstoppe5@umn.edu');
INSERT INTO student (sid, name, gender, email) VALUES (587, 'Helen-elizabeth Gerber', 'F', 'hgerber6@netscape.com');
INSERT INTO student (sid, name, gender, email) VALUES (708, 'Ivonne Biddell', 'F', 'ibiddell7@dmoz.org');
INSERT INTO student (sid, name, gender, email) VALUES (416, 'Karl Paoletto', 'M', 'kpaoletto8@sohu.com');
INSERT INTO student (sid, name, gender, email) VALUES (693, 'Birgit Gentle', 'F', 'bgentle9@who.int');
INSERT INTO student (sid, name, gender, email) VALUES (614, 'Jacques Degoey', 'M', 'jdegoeya@spiegel.de');
INSERT INTO student (sid, name, gender, email) VALUES (694, 'Bette-ann Hoffmann', 'F', 'bhoffmannb@plala.or.jp');
INSERT INTO student (sid, name, gender, email) VALUES (266, 'Mayer Lowry', 'M', 'mlowryc@ning.com');
INSERT INTO student (sid, name, gender, email) VALUES (647, 'Hillary Geratt', 'F', 'hgerattd@examiner.com');
INSERT INTO student (sid, name, gender, email) VALUES (173, 'Thorn Harome', 'M', 'tharomee@networksolutions.com');
INSERT INTO student (sid, name, gender, email) VALUES (909, 'Gawain Lamberti', 'M', 'glambertif@bloglines.com');
INSERT INTO student (sid, name, gender, email) VALUES (594, 'Simeon McNicol', 'M', 'smcnicolg@google.nl');
INSERT INTO student (sid, name, gender, email) VALUES (731, 'Blithe MacShirie', 'F', 'bmacshirieh@list-manage.com');
INSERT INTO student (sid, name, gender, email) VALUES (951, 'Araldo Griswood', 'M', 'agriswoodi@hp.com');
INSERT INTO student (sid, name, gender, email) VALUES (313, 'Glenna Daid', 'F', 'gdaidj@home.pl');
INSERT INTO student (sid, name, gender, email) VALUES (674, 'Doloritas Kleuer', 'F', 'dkleuerk@buzzfeed.com');
INSERT INTO student (sid, name, gender, email) VALUES (947, 'Chaim Smidmoor', 'M', 'csmidmoorl@fc2.com');
INSERT INTO student (sid, name, gender, email) VALUES (953, 'Tom Grier', 'M', 'tgrierm@dailymail.co.uk');
INSERT INTO student (sid, name, gender, email) VALUES (298, 'Germayne Espasa', 'M', 'gespasan@ted.com');
INSERT INTO student (sid, name, gender, email) VALUES (295, 'Skipp Laird', 'M', 'slairdo@friendfeed.com');
INSERT INTO student (sid, name, gender, email) VALUES (465, 'Nicolle Artist', 'F', 'nartistp@fema.gov');
INSERT INTO student (sid, name, gender, email) VALUES (998, 'Shayla Kilby', 'F', 'skilbyq@drupal.org');
INSERT INTO student (sid, name, gender, email) VALUES (163, 'Kimbra Clatworthy', 'F', 'kclatworthyr@angelfire.com');
INSERT INTO student (sid, name, gender, email) VALUES (744, 'Goldarina Meachem', 'F', 'gmeachems@canalblog.com');
INSERT INTO student (sid, name, gender, email) VALUES (902, 'Ianthe Langmead', 'F', 'ilangmeadt@who.int');
INSERT INTO student (sid, name, gender, email) VALUES (996, 'Cherilyn Clemonts', 'F', 'cclemontsu@symantec.com');
INSERT INTO student (sid, name, gender, email) VALUES (750, 'Richmound Cubbini', 'M', 'rcubbiniv@odnoklassniki.ru');
INSERT INTO student (sid, name, gender, email) VALUES (346, 'Valina Heaker', 'F', 'vheakerw@apache.org');
INSERT INTO student (sid, name, gender, email) VALUES (605, 'Angelico Antoniewski', 'M', 'aantoniewskix@cam.ac.uk');
INSERT INTO student (sid, name, gender, email) VALUES (378, 'Euell Payne', 'M', 'epayney@xing.com');
INSERT INTO student (sid, name, gender, email) VALUES (608, 'Linnet Keeri', 'F', 'lkeeriz@cornell.edu');
INSERT INTO student (sid, name, gender, email) VALUES (235, 'Corliss Sparwell', 'F', 'csparwell10@umn.edu');
INSERT INTO student (sid, name, gender, email) VALUES (426, 'Alistair Ozintsev', 'M', 'aozintsev11@cdbaby.com');
INSERT INTO student (sid, name, gender, email) VALUES (145, 'Jacinta Chace', 'F', 'jchace12@mozilla.com');
INSERT INTO student (sid, name, gender, email) VALUES (233, 'Jed Limb', 'M', 'jlimb13@nih.gov');
INSERT INTO student (sid, name, gender, email) VALUES (321, 'Austin Cradoc', 'M', 'acradoc14@imageshack.us');
INSERT INTO student (sid, name, gender, email) VALUES (492, 'Mommy Dayes', 'F', 'mdayes15@chicagotribune.com');
INSERT INTO student (sid, name, gender, email) VALUES (208, 'Bertrand Tumelty', 'M', 'btumelty16@free.fr');
INSERT INTO student (sid, name, gender, email) VALUES (833, 'Hersch Havers', 'M', 'hhavers17@accuweather.com');
INSERT INTO student (sid, name, gender, email) VALUES (695, 'Kerrie Handyside', 'F', 'khandyside18@wunderground.com');
INSERT INTO student (sid, name, gender, email) VALUES (709, 'Winnie Barczewski', 'M', 'wbarczewski19@harvard.edu');
INSERT INTO student (sid, name, gender, email) VALUES (850, 'Lyndsey Frosch', 'F', 'lfrosch1a@linkedin.com');
INSERT INTO student (sid, name, gender, email) VALUES (498, 'Chucho Wainwright', 'M', 'cwainwright1b@scribd.com');
INSERT INTO student (sid, name, gender, email) VALUES (134, 'Doris Ortet', 'F', 'dortet1c@washington.edu');
INSERT INTO student (sid, name, gender, email) VALUES (138, 'Rowan Dioniso', 'M', 'rdioniso1d@blog.com');
INSERT INTO student (sid, name, gender, email) VALUES (842, 'Ola Redwall', 'F', 'oredwall1e@bizjournals.com');
INSERT INTO student (sid, name, gender, email) VALUES (826, 'Harry Pritchett', 'M', 'hpritchett1f@latimes.com');
INSERT INTO student (sid, name, gender, email) VALUES (529, 'Alejandro Broodes', 'M', 'abroodes1g@harvard.edu');
INSERT INTO student (sid, name, gender, email) VALUES (135, 'Conan Vondra', 'M', 'cvondra1h@surveymonkey.com');
INSERT INTO student (sid, name, gender, email) VALUES (650, 'Meredith Handover', 'M', 'mhandover1i@msn.com');
INSERT INTO student (sid, name, gender, email) VALUES (248, 'Arte Malyon', 'M', 'amalyon1j@skype.com');
INSERT INTO student (sid, name, gender, email) VALUES (414, 'Bride Basilotta', 'F', 'bbasilotta1k@nhs.uk');
INSERT INTO student (sid, name, gender, email) VALUES (223, 'Nat Tebbut', 'F', 'ntebbut1l@seattletimes.com');
INSERT INTO student (sid, name, gender, email) VALUES (751, 'Constantin Heimann', 'M', 'cheimann1m@biglobe.ne.jp');
INSERT INTO student (sid, name, gender, email) VALUES (338, 'Deloris Fincken', 'F', 'dfincken1n@weather.com');
INSERT INTO student (sid, name, gender, email) VALUES (310, 'Gaby Roddick', 'F', 'groddick1o@ft.com');
INSERT INTO student (sid, name, gender, email) VALUES (515, 'Urbain Wipper', 'M', 'uwipper1p@berkeley.edu');
INSERT INTO student (sid, name, gender, email) VALUES (210, 'Octavius des Remedios', 'M', 'odes1q@mysql.com');
INSERT INTO student (sid, name, gender, email) VALUES (213, 'Chico Pendrigh', 'M', 'cpendrigh1r@usnews.com');
INSERT INTO student (sid, name, gender, email) VALUES (629, 'Konstanze Audley', 'F', 'kaudley1s@friendfeed.com');
INSERT INTO student (sid, name, gender, email) VALUES (239, 'Dante Henriques', 'M', 'dhenriques1t@samsung.com');
INSERT INTO student (sid, name, gender, email) VALUES (716, 'Cicily Hatchell', 'F', 'chatchell1u@adobe.com');
INSERT INTO student (sid, name, gender, email) VALUES (878, 'Mitch Cowoppe', 'M', 'mcowoppe1v@hubpages.com');
INSERT INTO student (sid, name, gender, email) VALUES (203, 'Berenice Farran', 'F', 'bfarran1w@hao123.com');
INSERT INTO student (sid, name, gender, email) VALUES (641, 'Leland Gipp', 'M', 'lgipp1x@vkontakte.ru');
